services:

  # ---------------------------------------------------------------------------
  # Serveur Tomcat — déployé depuis le WAR construit avec Maven
  # ---------------------------------------------------------------------------
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-tomcat
    ports:
      - "8085:8080"
